---
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html

- name: create and run docker-compose
  hosts: docker1
  tasks:
    - name: Create a Directory
      file:
        path: ./wordpress
        state: directory 

    - name: create docker-compose file at the root of project
      file:
        path: ./wordpress/docker-compose.yaml
        state: touch

    - name: Insert config into the docker-compose file
      copy:
        dest: ./wordpress/docker-compose.yaml
        content: |
          version: "3"
          services:
            wordpress:
              image: wordpress
              ports:
                - "8080:80"
              depends_on:
                - mysql
              environment:
                WORDPRESS_DB_HOST: mysql
                WORDPRESS_DB_USER: root
                WORDPRESS_DB_PASSWORD: "Ubuntu"
                WORDPRESS_DB_NAME: wordpress
            
            mysql:
              image: "mysql:5.7"
              environment:
                MYSQL_DATABASE: wordpress
                MYSQL_ROOT_PASSWORD: "Ubuntu"
              volumes:
                - ./mysql:/var/lib/mysql
 
          
    - name: Build docker-compose containers
      command: docker-compose up -d
      args:
        chdir: ./wordpress


