---
#https://doc.traefik.io/traefik/getting-started/quick-start/
- name: create and run docker-compose for treafik
  hosts: docker4
  tasks:
    - name: Create Directory Nginx-loadbalancer
      file:
        path: ./nginx-loadbalancer
        state: directory 
   
    - name: Create Directory app1
      file:
        path: ./nginx-loadbalancer/app1
        state: directory
    
    - name: Create Directory app2
      file:
        path: ./nginx-loadbalancer/app2
        state: directory

    - name: Create Directory nginx
      file:
        path: ./nginx-loadbalancer/nginx
        state: directory


    - name: create docker-compose file at the root of project
      file:
        path: ./nginx-loadbalancer/docker-compose.yaml
        state: touch

    - name: create file app1.py
      file:
        path: ./nginx-loadbalancer/app1/app1.py
        state: touch

    - name: create file requirements.py
      file:
        path: ./nginx-loadbalancer/app1/requirements.txt
        state: touch

    - name: create file Dockerfile
      file:
        path: ./nginx-loadbalancer/app1/Dockerfile
        state: touch

    - name: create file app2.py
      file:
        path: ./nginx-loadbalancer/app2/app2.py
        state: touch

    - name: create file requirements.py
      file:
        path: ./nginx-loadbalancer/app2/requirements.txt
        state: touch

    - name: create file Dockerfile
      file:
        path: ./nginx-loadbalancer/app2/Dockerfile
        state: touch

    - name: create file nginx.conf
      file:
        path: ./nginx-loadbalancer/nginx/nginx.conf
        state: touch

    - name: create file Dockerfile
      file:
        path: ./nginx-loadbalancer/nginx/Dockerfile
        state: touch




    - name: Insert config into the docker-compose file
      copy:
        dest: ./nginx-loadbalancer/docker-compose.yaml
        content: |
          version: '3'
          services:
            app1:
              build: ./app1
              ports:
              - "5001:5000"
            app2:
              build: ./app2
              ports:
              - "5002:5000"
            nginx:
              build: ./nginx 
              ports:
              - "8080:80"
              depends_on:
                - app1
                - app2

    - name: Insert config into the docker-compose file
      copy:
        dest: ./nginx-loadbalancer/app1/app1.py
        content: |
          from flask import request, Flask
          import socket

          app1 = Flask(__name__)

          @app1.route('/')
          def hello_world():
              return '<h1>Hello from server 1</h2>'

          if __name__ == '__main__':
            app1.run(debug=True, host='0.0.0.0')


    - name: Insert config into the docker-compose file
      copy:
        dest: ./nginx-loadbalancer/app1/requirements.txt
        content: |
          Flask==3.0.3
          Werkzeug==3.0.0
          

    - name: Insert config into the docker-compose file
      copy:
        dest: ./nginx-loadbalancer/app1/Dockerfile
        content: |
          FROM python:3
          COPY ./requirements.txt /requirements.txt
          WORKDIR /
          RUN pip install -r requirements.txt
          COPY . /
          ENTRYPOINT [ "python3" ]
          CMD [ "app1.py" ]



    - name: Insert config into the docker-compose file
      copy:
        dest: ./nginx-loadbalancer/app2/app2.py
        content: |
          from flask import request, Flask

          app1 = Flask(__name__)


          @app1.route('/')
          def hello_world():
              return '<h1>Hello from server 2</h2>'


          if __name__ == '__main__':
            app1.run(debug=True, host='0.0.0.0')


    - name: Insert config into the docker-compose file
      copy:
        dest: ./nginx-loadbalancer/app2/requirements.txt
        content: |
          Flask==3.0.3
          Werkzeug==3.0.0
          

    - name: Insert config into the docker-compose file
      copy:
        dest: ./nginx-loadbalancer/app2/Dockerfile
        content: |
          FROM python:3
          COPY ./requirements.txt /requirements.txt
          WORKDIR /
          RUN pip install -r requirements.txt
          COPY . /
          ENTRYPOINT [ "python3" ]
          CMD [ "app2.py" ]



    - name: Insert config into the docker-compose file
      copy:
        dest: ./nginx-loadbalancer/nginx/Dockerfile
        content: |
          FROM nginx
          RUN rm /etc/nginx/conf.d/default.conf
          COPY nginx.conf /etc/nginx/conf.d/default.conf
    

    - name: Insert config into the docker-compose file
      copy:
        dest: ./nginx-loadbalancer/nginx/nginx.conf
        content: |
          upstream loadbalancer {
              server 172.17.0.1:5001 weight=5;
              server 172.17.0.1:5002 weight=5;
          }

          server {
              location / {
                  proxy_pass http://loadbalancer;
              }
          }     
                    
    - name: Build nginx loadbalancer
      command: docker-compose up -d 
      args:
          chdir: ./nginx-loadbalancer

   
