---
- name: create and run docker-compose
  hosts: docker3
  tasks:
    - name: disable firewall
      command: ufw disable
    
    # - name: stop firewall
    #   command: systemctl stop firewalld

    - name: flush iptabels
      command: iptables -F
    
    - name: create docker-compose file at the root of project
      file:
        path: ./docker-compose.yaml
        state: touch

    - name: Insert config into the docker-compose file
      copy:
        dest: ./docker-compose.yaml
        content: |
          version: '3.9'
          services:
            container_1:
              image: alpine:latest
              container_name: container_1
              networks:
                net1:
                  ipv4_address: 192.168.100.2  
              cap_add:
                - NET_ADMIN  
              command: >
                /bin/sh -c "apk add --no-cache iputils iproute2 && 
                ip route add 192.168.200.0/24 via 192.168.100.254 && 
                tail -f /dev/null"  # Install tools and add route

            container_2:
              image: alpine:latest
              container_name: container_2
              networks:
                net2:
                  ipv4_address: 192.168.200.2  
              cap_add:
                - NET_ADMIN  
              command: >
                /bin/sh -c "apk add --no-cache iputils iproute2 && 
                ip route add 192.168.100.0/24 via 192.168.200.254 && 
                tail -f /dev/null"  # Install tools and add route

            router:
              image: alpine:latest
              container_name: router
              privileged: true  
              networks:
                net1:
                  ipv4_address: 192.168.100.254  
                net2:
                  ipv4_address: 192.168.200.254  
              command: >
                /bin/sh -c "apk add --no-cache iproute2 && 
                sysctl -w net.ipv4.ip_forward=1 && 
                tail -f /dev/null"  # Install tools

          networks:
            net1:
              driver: bridge
              ipam:
                config:
                  - subnet: 192.168.100.0/24

            net2:
              driver: bridge
              ipam:
                config:
                  - subnet: 192.168.200.0/24
          
    - name: Build docker-compose containers
      command: docker-compose up -d

- name: add ip routes to docker container
  hosts: pve1270
  tasks:
    - name: add route to 192.168.100.0/24
      command: ip route add 192.168.100.0/24 via 10.24.27.42

    - name: add route to 192.168.200.0/24
      command: ip route add 192.168.200.0/24 via 10.24.27.42

