apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.Claim_name }}
  namespace: {{ .Values.namespace }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mysql_storge_path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.Claim_name }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}