apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespaces }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appname }}
  ports:
    - port: {{ .Values.container_port }}
      targetPort: {{ .Values.container_port }}
      nodePort: {{ .Values.NodePort }}