--- 
#https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html
#https://gist.github.com/Finkregh/c7aafa925f28c531cf1b3eebfdcd474f
#https://www.educba.com/ansible-register/
#made by Noa

- name: Create and start a proxmox container
  hosts: pve1270
  vars:
    id: 202
    hostname: wordpress1
    gw: 10.24.27.1
    ip: 10.24.27.24/24
    cores: 1
    memory: 1024
    storage: vm-pool
    password: Ubuntu
    netint: eth0
    bridge: vmbr0
    type: veth
    start_wait_time: 10
    firewall: True
    rate: 50
    dns: 1.1.1.1
    gb: 30


    containers:
      - { id: 203, hostname: wordpress2, gw: 10.24.27.1, ip: 10.24.27.25/24 } 
      - { id: 204, hostname: wordpress3, gw: 10.24.27.1, ip: 10.24.27.26/24 }

  tasks:
  - name: Create a new container
    shell: |
      pct create {{ id }} files-storage:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst \      
        -hostname "{{ hostname }}" \
        -cores {{ cores }} \
        -memory {{ memory }} \
        -storage "{{ storage }}" \
        -password "{{ password }}" \
        -net0 name={{ netint }},bridge={{ bridge }},gw={{ gw }},ip={{ ip }},firewall={{ firewall }},type={{ type }},rate={{ rate }} \
        -nameserver "{{ dns }}" \
        -rootfs "{{ storage }}:{{ gb }}" \

        pct push {{ id }} /root/scripts/wordpress.sh /root/wordpress.sh
        pct exec {{ id }} chmod u+x /root/wordpress.sh
        pct exec {{ id }} /root/wordpress.sh
        
    args:
      executable: /bin/bash


  - name: Start container
    shell: |
      pct start {{ id }} \
    args:
      executable: /bin/bash
  
  - name: maak een back-up template met wordpress #back up template in cluster
    shell: |
      vzdump {{ id }}  --compress zstd --mode stop --dumpdir /mnt/pve/files-storage/template/cache/ 
    args:
      executable: /bin/bash

