---
#made by Noa
- name: Create and start a proxmox container
  hosts: wordpress1
  
  tasks:
  - name: add users
    user:
      name: "{{ item }}"
      state: present

  - ansible.builtin.user:
      name: "{{ item }}"
      shell: /bin/bash
    
    loop:
      - hans
      - piet
    