---
#made by Noa
- name: Create and start a proxmox container
  hosts: pve1270
  vars:
 
    #contaier configuration
    virtualmachine: 
      - { id: 201, hostname: espo-crm1, gw: 10.24.27.1, ip: 10.24.27.31/24 }
      - { id: 202, hostname: espo-crm2, gw: 10.24.27.1, ip: 10.24.27.32/24 }
      - { id: 203, hostname: espo-crm3, gw: 10.24.27.1, ip: 10.24.27./24 } 
   

  tasks:

  - name: Create a multiple containers
    shell: |
      qm clone 1000 {{ item.id }} --name {{ item.hostname }} -full -storage vm-pool
      qm set 201 --ipconfig0 ip={{ item.ip }},gw={{ item.gw }}
      qm set 201 --nameserver 1.1.1.1
      qm set 201 --core 2 --memory 2048 --balloon 0
      qm start 201
    args:
      executable: /bin/bash
    
    loop:
      "{{ virtualmachine }}"

  - name: Start container
    shell: |
      pct start {{ item.id }} 
    args:
      executable: /bin/bash
    loop:
      "{{ virtualmachine }}"

 