#cat << EOF | tee /mnt/pve/files-storage/snippets/vendor.yaml
#cloud-config
users:
  - default

packages:
  - wget

runcmd:
  - apt update
  - apt upgrade -y
  - apt install -y qemu-guest-agent
  - systemctl start qemu-guest-agent
  - wget -O /tmp/espo-crm_install.sh https://raw.githubusercontent.com/jhbos/SDI2425-437407/refs/heads/main/espo-crm/espo-crm_install.sh?token=GHSAT0AAAAAACXA4AZKB66GLLKWUVDFUUPOZYBZCWQ
  - chmod +x /tmp/espo-crm_install.sh
  - /tmp/espo-crm_install.sh



 