---
- name: Create and start a Proxmox container
  hosts: pve1270
  vars:
    #contianer info
    id: 206
    hostname: wordpress

    #basic configuration
    cores: 1
    memory: 1024
    swap: 512
    storage: vm-pool
    gb: 16
    password: Ubuntu
    
    #networking
    net0_name: eth0
    bridge: vmbr0
    firewall: 1
    gw: 10.24.27.1
    ip: 10.24.27.32/24
    type: veth
    dns: 1.1.1.1


  tasks:
    - name: Create a new container
      shell: |
        pct create {{ id }} files-storage:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst \
          -hostname {{ hostname }} \
          -cores {{ cores }} \
          -memory {{ memory }} \
          -swap {{ swap }} \
          -storage {{ storage }} \
          -rootfs "{{ storage }}:{{ gb }}" \
          -password {{ password }} \
          -net0 name={{ net0_name }},bridge={{ bridge }},firewall={{ firewall }},gw={{ gw }},ip={{ ip }},type={{ type }} \
          -nameserver {{ dns }} &&\
        pct start {{ id }}

      args:
        executable: /bin/bash

    - name: push enable.sh 
      shell: |
        pct push {{ id }} /root/scripts/test.sh /root/test.sh
        pct exec {{ id }} chmod u+x /root/test.sh
        pct exec {{ id }} /root/test.sh
      
      args:
        executable: /bin/bash

    - include_tasks: wordpress.yaml


